import random
import webbrowser

GITHUB_IMAGE_URL = "https://raw.githubusercontent.com/Alex-biochem/Albumin-educational-program/main/AF-P02768-F1.jpg"
WIKIPEDIA_TEXT = "Search Wikipedia for: Serum albumin"

YELLOW = "\033[93m"
RESET = "\033[0m"

AMINO_ACIDS = "ACDEFGHIKLMNPQRSTVWY"


def get_albumin_sequence():
    return "MKWVTFISLLFLFSSAYSRGVFRRDTHKSEIAHRFKDLGEENFKALVLIAFAQYLQQCPFEDHVKLVNEVTEFAKTCVADESAENCDKSLHTLFGDKLCTVATLRETYGEMADCCAKQEPERNECFLSHKDDSPDLPKLKPDPNTLCDEFKADEKKFWGKYLYEIARRHPYFYAPELLFFAKRYKAAFTECCQAADKAACLLPKLDELRDEGKASSAKQRLKCASLQKFGERAFKAWAVARLSQRFPKAEFAEVSKLVTDLTKVHTECCHGDLLECADDRADLAKYICENQDSISSKLKECCEKPLLEKSHCIAEVEKDAIPENLPPLTADFAEDKDVCKNYAEAKDVFLGMFLYEYARRHPDYSVVLLLRLAKTYETTLEKCCAAADPHECYAKVFDEFKPLVEEPQNLIKQNCDQFEKLGEYGFQNALIVRYTRKVPQVSTPTLVEVSRNLGKVGSKCCKHPEAKRMPCAEDYLSVVLNQLCVLHEKTPVSEKVTKCCTESLVNRRPCFSALEVDETYVPKEFNAETFTFHADICTLSEKERQIKKQTALVELVKHKPKATKEQLKAVMDDFAAFVEKCCKADDKETCFAEEGKKLVAASQAALGL"


def wrap_sequence(seq, width=80):
    for i in range(0, len(seq), width):
        print(seq[i:i + width])


def open_alphafold_image():
    webbrowser.open(GITHUB_IMAGE_URL)


def mutate_sequence(sequence):
    position = random.randint(0, len(sequence) - 1)
    original_residue = sequence[position]

    possible_mutations = [aa for aa in AMINO_ACIDS if aa != original_residue]
    new_residue = random.choice(possible_mutations)

    mutated_sequence = sequence[:position] + new_residue + sequence[position + 1:]
    return mutated_sequence, position, original_residue, new_residue


def highlight_mutation(original, mutated):
    highlighted_original = []
    highlighted_mutated = []

    for original_residue, mutated_residue in zip(original, mutated):
        if original_residue != mutated_residue:
            highlighted_original.append(f"{YELLOW}{original_residue}{RESET}")
            highlighted_mutated.append(f"{YELLOW}{mutated_residue}{RESET}")
        else:
            highlighted_original.append(original_residue)
            highlighted_mutated.append(mutated_residue)

    return "".join(highlighted_original), "".join(highlighted_mutated)


def main():
    print("Hello! This educational program shows the human albumin protein.")
    print("Note: when you see 'Press Enter to proceed', press the Enter key on your keyboard.")
    input("Press Enter to proceed...")

    print("The program will show the 3D structure of albumin generated by AlphaFold.")
    input("Press Enter to proceed...")

    answer = input("Would you like to proceed (yes/no)? ").strip().lower()

    if answer != "yes":
        print("Have a great day!")
        return

    print("Albumin is a protein made of amino acid residues.")
    print("It helps bind and transport fatty acids and other molecules in the blood.")
    input("Press Enter to proceed...")

    sequence = get_albumin_sequence()
    print("Here is the primary structure of human albumin, where each letter represents one amino acid residue:")
    wrap_sequence(sequence)
    input("Press Enter to proceed...")

    print("Like many proteins, albumin folds into domains that contribute to its structure and function.")
    input("Press Enter to proceed...")

    print("The program will now open a GitHub-hosted image of the 3D structure of albumin.")
    input("Press Enter to proceed...")
    open_alphafold_image()

    print("Albumin, like any other protein, can acquire mutations.")
    input("Press Enter to proceed...")

    print("Our program will now model a random mutation in the primary sequence.")
    input("Press Enter to proceed...")

    mutated_sequence, position, original_residue, new_residue = mutate_sequence(sequence)

    print("Here is the sequence with the mutation:")
    wrap_sequence(mutated_sequence)
    input("Press Enter to proceed...")

    print("It can be difficult to find the mutation manually.")
    print("The program will now compare the original and mutated sequences and highlight the mutation in yellow.")
    input("Press Enter to proceed...")

    highlighted_original, highlighted_mutated = highlight_mutation(sequence, mutated_sequence)

    print("\nOriginal sequence:")
    wrap_sequence(highlighted_original)

    print("\nMutated sequence:")
    wrap_sequence(highlighted_mutated)

    print(f"\nMutation details: position {position + 1}, {original_residue} -> {new_residue}")
    input("Press Enter to proceed...")

    learn_more = input("Would you like to learn more about albumin? (yes/no) ").strip().lower()

    if learn_more == "yes":
        print("For more information:")
        print(WIKIPEDIA_TEXT)

    print("Have a great day!")


if __name__ == "__main__":
    main()



